cd ~/Desktop
mkdir week2 
cd week2
mkdir monday tuesday wednesday thursday friday 
cd monday
touch spanish.monday
touch english.monday 
touch tutorial.monday
touch math.monday
cd ../
cd tuesday
touch spanish.tuesday
touch chemistry.tuesday
touch ushistory.tuesday
touch art.tuesday
cd ../
cd wednesday 
touch spanish.wednesday
touch english.wednesday
touch tutorial.wednesday
touch math.wednesday
cd ../
cd thursday
touch spanish.thursday
touch chemistry.thursday
touch ushistory.thursday
touch tutorial.thursday
cd ../
cd friday
touch spanish.friday
touch english.friday
touch chemistry.friday
touch tutorial.friday
touch ushistory.friday
touch math.friday
touch health.friday